making project using numpy....


level 1 numpy array  + basic data

In [12]:
# import numpy as np

# marks = np.array([
#     [78, 49, 90, 60],
#     [40, 50, 30, 20]
# ])

# print("marks", marks)
# print("Numnber of subjects: ", marks.size)
# print("Dimensions:", marks.ndim)
# print("Shape: ", marks.shape)
# print("Maths:", marks[0])
# print("Python:", marks[1])


marks [[78 49 90 60]
 [40 50 30 20]]
Numnber of subjects:  8
Dimensions: 2
Shape:  (2, 4)
Maths: [78 49 90 60]
Python: [40 50 30 20]


Level 2 total average , highest , lowest

In [21]:
# import numpy as np
# marks = np.array([78, 85, 90, 67, 78])

# total = np.sum(marks)
# average = np.mean(marks)
# highest  = np.max(marks)
# lowest = np.min(marks)

# subjects = np.array([
#     "Maths",
#     "Pyhsics",
#     "Chemistry",
#     "English",
#     "Python"
# ])

# highest_index = np.argmax(marks)

# print("Highest subject:", subjects[highest_index])
# print("Highest marks:", marks[highest_index])

# print("Marks:", marks)
# print("Total:", total)
# print("Average:", average)
# print("Highest:", highest)
# print("Lowest:", lowest)

Level 3 -- Pass / fail + filtering

In [28]:
# import numpy as np

# marks = np.array([ 80, 78, 40, 90, 32])

# print("Marks:", marks)
# print("pass/fail:")

# print(marks >= 40)

# failing_marks = marks[marks < 40]
# print("failing marks:", failing_marks)

# passing_average = np.mean(marks[marks >= 40])
# print("Passing average:", passing_average)

# print("Standard deviation:", np.std(marks))

Level 4 -- proper mini project

In [33]:
import numpy as np

student = np.array(["Rahul", "Aman","Neha","Ravi"])

marks = np.array([
    [78, 85, 67, 90, 72],
    [55, 65, 70, 60, 80],
    [92, 88, 95, 85, 90],
    [35, 45, 40, 38, 50]
])
print("student:")
print(student)

print("\nMarks:")
print(marks)

total = np.sum(marks, axis=1)
print("Total marks :", total)

average = np.mean(marks, axis=1)
print("Average:", average)

highest = np.max(marks, axis=1)
print("Highest:", highest)

lowest = np.min(marks, axis=1)
print("lowest:", lowest)



student:
['Rahul' 'Aman' 'Neha' 'Ravi']

Marks:
[[78 85 67 90 72]
 [55 65 70 60 80]
 [92 88 95 85 90]
 [35 45 40 38 50]]
Total marks : [392 330 450 208]
Average: [78.4 66.  90.  41.6]
Highest: [90 80 95 50]
lowest: [67 55 85 35]
