In [1]:
# 

# # ##Numpy array and basics
# # learn about numpy with chai aur Code 
# arr_1d = np.array([1, 2, 3, 4, 5]) 
# print("1D array: " , arr_1d)

# arr_2d = np.array([[1,2,3], [4,5,6]])
# print("2D array: ", arr_2d)

list vs numpay array difference

In [2]:
# py_list = [1, 2 ,3]
# print("Python list multiplication ", py_list)
# np_array = np.array([1, 2, 3])  # element-wise multiplication
# print("python array multiplication ", np_array * 2)



In [3]:
# import time
# start = time.time()
# py_list = [l*2 for i in range(100000)]
# int("\n Numpy operations:", time.time()- start)

# start = time.time()
# np_array = np.array(10000) * 2
# print("\n Numpy operation time:" , time.time() -start)

In [4]:
# arry_1d = [1,2,3, 4, 5]
# print(arry_1d)

In [5]:
# marks = [70, 80, 90, 60]

# new_marks = []

# for x in marks:
#     new_marks.append(x + 5)

# print("new_marks")

In [6]:
# import numpy as np
# marks = np.array([70, 80, 90, 60])

# print(marks + 5)

level 2 -- Numpy array

In [7]:
# import numpy as np

# arr = np.array([10, 20, 30 ,40])

# print(arr)

python list vs numpy array

In [8]:
# import numpy as np

# a = np.array([1,2, 3, 4])

# print(type(a))


level 3 -- 1D, 2D, 3D Arrays

In [9]:
# import numpy as np

# arr = np.array([1, 2, 3, 4 , 5])
# print(arr)

# arr = np.array([
#     [1, 2, 3],
#     [4, 5, 6]
# ])
# print(arr)

# arr = np.array([
#     [
#        [
#         [
#             [
#                 [
#                     [
#                         [
#                             [ 2, 3],
#                             [3 , 8]
#                         ]
#                         ]
#                     ]
#                 ]
#             ]
#         ]
#        ]
#     ],
#     [
#         [
#             [
#                 [
#                     [
#                         [ 3, 9],
#                         [5m
#                     ]
#                 ]
#             ]
#         ]
#     ]
# ])

# print(arr)

level 4 --- Important array properties

In [10]:
# import numpy as np
# arr = np.array([
#     [1, 2, 3],
#     [4, 5, 6]
# ])

# print(arr.itemsize)

level 5 -- different ways to create arrays 


In [11]:
# import numpy as np

# a = np.array([1, 2, 3, 4 , 5])
# print(np.zeros)

creating array from scratch

In [ ]:
# import numpy as np
# zeros = np.zeros((3 , 4))
# print("zeros array :", zeros)

# ones = np.ones((4, 5))
# print("one array:\n ", ones)

# full = np.full((3, 3), 1)
# print("full array: \n", full)


zeros array : [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array:
  [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
full array: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


startingfromzerotoadvancelevel

In [ ]:
# import numpy as np
# numnber  = np.array([1,2,3,4,5])
# print(numnber)

[1 2 3 4 5]


python list vs NUmpay array


In [ ]:
# a  = np.array([1, 2, 3])
# b = np.array([2, 3, 2])
# print(a+b)


[3 5 5]


Level 2 Numpay array

In [ ]:
#1d array

# arr = np.array([10, 20, 30, 40, 50])
# print(arr)

#2d arrray

# arr = np.array([
#     [1, 2, 3],
#     [3, 4, 5]
# ])
# print(arr)

# #3d array

# arr = np.array([
#     [
#         [1, 2],
#         [3, 4]
#     ],
#     [
#         [5, 6],
#         [6, 7]
#     ]
    
# ])
# print(arr)

# #ndim

# arr = np.array([[1, 2, 3], [4, 5, 6]])
# print(arr.ndim)

# #shape 
# arr = np.array([
#     [1, 2, 3],
#     [4, 5, 6]
# ])
# print(arr.size)
# #dtype

# arr = np.array([1, 2, 3, 4, 5])
# print(arr.dtype)

# import numpy as np

# arr = np.array([1, 2, 3])

# print(arr.itemsize)

8


level 3 -- Array creation

In [ ]:
#np.zeroes
# import numpy as np

# arr = np.zeros((2, 3))

# print(arr)

#np.one()

# arr = np.ones((2, 3))

# print(arr)

# np.full()

# arr = np.full((2, 3), 100)

# print(arr)

# np.arange

# arr = np.arange(1, 10)

# print(arr)

# arr = np.arange(0, 20, 2)
# print(arr)

# arr = np.linspace(0, 10, 5)

# print(arr)

[1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0.   2.5  5.   7.5 10. ]


level 4 -- indexing

In [ ]:
# import numpy as np

# # arr = np.array([10, 20, 30, 40, 50])

# # print(arr[0])
# # print(arr[2])
# # print(arr[-1])

# #2 d indexing

# arr = np.array([
#     [10, 20, 30],
#     [40, 50, 60]
# ])

# print(arr[1, 2])

60


Level 4 slicing 

In [ ]:
# import numpy as np

# arr = np.array([10, 20, 30, 40, 50])

# print(arr[1: 4])
# print(arr[::2])
# print(arr[::-1])



[20 30 40]
[10 30 50]
[50 40 30 20 10]


Level 5 -- slicing 

In [ ]:
# import numpy as np

# # 2dslicing

# arr = np.array([
#     [1, 2, 3],
#     [4,5, 6],
#     [6, 3 , 2]
# ])

# print(arr[::2])
# print(arr[:, 1:])

[[1 2 3]
 [6 3 2]]
[[2 3]
 [5 6]
 [3 2]]


level 6 -- modifiying arrays

In [44]:
# import numpy as np

# arr = np.array([10, 20, 30, 40])

# # arr[1] = 200
# # arr[0, 1] = 999
# print(arr[0,1])

level 7 arithmethic operations

In [48]:
# a = np.array([1, 2, 3])
# b = np.array([4, 5, 6])

# print(a + b)
# print(a - b)
# print(a * b)

# print(a / b)
# # print(a ** 2)
# 3scalar operations
# arr = np.array([1, 2, 3, 4])

# print(arr * 10)

# print(arr + 5)

level 8 --- universal function (ufuncs)


In [ ]:
# import numpy as np
# arr = np.array([1, 4, 9, 16])

# # print(np.sqrt(arr))
# np.exp(arr)
# np.log(arr)
# np.abs([-10, 5, -7])
# np.sin(arr)
# np.cos(arr)
# np.tan(arr)

array([ 1.55740772,  1.15782128, -0.45231566,  0.30063224])

Vector ,Matrix and Tensor

In [ ]:
import numpy as np
vector = np.array([1, 2, 3])
print("Vector:", vector)

matrix = np.array([[1, 2, 3],
[4, 5, 6]])
print("Vector: ", matrix )

tensor = np.array([[[1, 2], [3, 4]],
[[5, 6], [7, 8]]])
print('Tensor:', tensor)



Vector: [1 2 3]
Vector:  [[1 2 3]
 [4 5 6]]
Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array properties


In [11]:
arr = np.array([[1, 2, 3],
[4, 5, "6.7"]])
print("Shape" , arr.shape)
print("Dimension", arr.ndim)
print("Size ",arr.size)
print("dtype",arr.dtype)

Shape (2, 3)
Dimension 2
Size  6
dtype <U21


Array Reshaping

In [18]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

raveled = reshaped.ravel()
print("\n raveled array", raveled)

#transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


numpy array operations


In [1]:
import numpy as np



In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Basic slicing", arr[2:7])
print("WIth step", arr[1:8:2])
print("Negative indexing",arr[-3])

Basic slicing [3 4 5 6 7]
WIth step [2 4 6 8]
Negative indexing 7


In [10]:
arr_2d = np.array([[1, 2, 3],
[4, 5,6],
[7, 8, 9]])

print("Specific element", arr_2d[1,2])
print("Entire Row: ",arr_2d[1])
print("Entire row:", arr_2d[:,1])

Specific element 6
Entire Row:  [4 5 6]
Entire row: [2 5 8]


Sorting


In [11]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

Sorted Array [1 1 2 3 4 5 6 9]
