In [ ]:
# 

# # ##Numpy array and basics
# # learn about numpy with chai aur Code 
# arr_1d = np.array([1, 2, 3, 4, 5]) 
# print("1D array: " , arr_1d)

# arr_2d = np.array([[1,2,3], [4,5,6]])
# print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


list vs numpay array difference

In [ ]:
# py_list = [1, 2 ,3]
# print("Python list multiplication ", py_list)
# np_array = np.array([1, 2, 3])  # element-wise multiplication
# print("python array multiplication ", np_array * 2)



In [3]:
# import time
# start = time.time()
# py_list = [l*2 for i in range(100000)]
# int("\n Numpy operations:", time.time()- start)

# start = time.time()
# np_array = np.array(10000) * 2
# print("\n Numpy operation time:" , time.time() -start)

In [ ]:
# arry_1d = [1,2,3, 4, 5]
# print(arry_1d)

[1, 2, 3, 4, 5]


In [ ]:
# marks = [70, 80, 90, 60]

# new_marks = []

# for x in marks:
#     new_marks.append(x + 5)

# print("new_marks")

new_marks


In [ ]:
# import numpy as np
# marks = np.array([70, 80, 90, 60])

# print(marks + 5)

[75 85 95 65]


level 2 -- Numpy array

In [ ]:
# import numpy as np

# arr = np.array([10, 20, 30 ,40])

# print(arr)

[10 20 30 40]


python list vs numpy array

In [ ]:
# import numpy as np

# a = np.array([1,2, 3, 4])

# print(type(a))


[1 2 3 4 5]


level 3 -- 1D, 2D, 3D Arrays

In [ ]:
# import numpy as np

# arr = np.array([1, 2, 3, 4 , 5])
# print(arr)

# arr = np.array([
#     [1, 2, 3],
#     [4, 5, 6]
# ])
# print(arr)

# arr = np.array([
#     [
#        [
#         [
#             [
#                 [
#                     [
#                         [
#                             [ 2, 3],
#                             [3 , 8]
#                         ]
#                         ]
#                     ]
#                 ]
#             ]
#         ]
#        ]
#     ],
#     [
#         [
#             [
#                 [
#                     [
#                         [ 3, 9],
#                         [5m
#                     ]
#                 ]
#             ]
#         ]
#     ]
# ])

# print(arr)

level 4 --- Important array properties

In [ ]:
# import numpy as np
# arr = np.array([
#     [1, 2, 3],
#     [4, 5, 6]
# ])

# print(arr.itemsize)

8


level 5 -- different ways to create arrays 


In [ ]:
# import numpy as np

# a = np.array([1, 2, 3, 4 , 5])
# print(np.zeros)

<built-in function zeros>
